spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        packages-to-scan: >
          org.axonframework.eventhandling.tokenstore,
          org.axonframework.modelling.saga.repository,
          org.axonframework.eventsourcing.eventstore.jpa
    show-sql: true

server:
  port: 8081
  servlet:
    context-path: /api

axon:
  serializer:
    events: jackson
    general: jackson
    messages: jackson
  serializer-security:
    allowed-types: >
      com.neu.eventsourcing.**,
      org.axonframework.**,
      java.util.**
    allowed-classes: >
      com.neu.eventsourcing.**,
      org.axonframework.**,
      java.util.**
  eventhandling:
    processors:
      scanner-events:
        mode: tracking
        thread-count: 1
  axonserver:
    enabled: false

logging:
  level:
    root: INFO
